export { default as Login } from './login'
export { default as Register } from './register'
export { default as Routines } from './routines'
export { default as SingleRoutine } from './singleRoutine'
export { default as AddRoutine} from './addRoutine'
export { default as MyRoutines } from './myRoutines'
export { default as EditRoutine } from './editRoutine'
export { default as Activities } from './activities'
export { default as SingleActivity } from './singleActivity'
export { default as AddActivity } from './addActivity'
export { default as EditActivity } from './editActivity'
export { default as AddActivityToRoutine } from './addActivityToRoutine'
export { default as EditRoutineActivity } from './editRoutineActivity'
export { default as Home } from './home'
export { default as RoutineSearch } from './routineSearch'
export { default as ActivitySearch } from './activitySearch'